In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
data = 'bank-full.csv'

In [3]:
data

'bank-full.csv'

In [7]:
df = pd.read_csv(data, sep=';')
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [8]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [19]:
features = ['age', 'job', 'marital', 'education', 'balance', 'housing',
       'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y']

In [20]:
df_full = df[features]

In [21]:
df_full

age           job   marital  education  balance housing    contact  \
0       58    management   married   tertiary     2143     yes    unknown   
1       44    technician    single  secondary       29     yes    unknown   
2       33  entrepreneur   married  secondary        2     yes    unknown   
3       47   blue-collar   married    unknown     1506     yes    unknown   
4       33       unknown    single    unknown        1      no    unknown   
...    ...           ...       ...        ...      ...     ...        ...   
45206   51    technician   married   tertiary      825      no   cellular   
45207   71       retired  divorced    primary     1729      no   cellular   
45208   72       retired   married  secondary     5715      no   cellular   
45209   57   blue-collar   married  secondary      668      no  telephone   
45210   37  entrepreneur   married  secondary     2971      no   cellular   

       day month  duration  campaign  pdays  previous poutcome    y  
0        5   may       261         1     -1         0  unknown   no  
1        5   may       151         1     -1         0  unknown   no  
2        5   may        76         1     -1         0  unknown   no  
3        5   may        92         1     -1         0  unknown   no  
4        5   may       198         1     -1         0  unknown   no  
...    ...   ...       ...       ...    ...       ...      ...  ...  
45206   17   nov       977         3     -1         0  unknown  yes  
45207   17   nov       456         2     -1         0  unknown  yes  
45208   17   nov      1127         5    184         3  success  yes  
45209   17   nov       508         4     -1         0  unknown   no  
45210   17   nov       361         2    188        11    other   no  

[45211 rows x 15 columns]

In [22]:
df_full.isna().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [23]:
edmode = df_full['education'].mode()
edmode

0    secondary
Name: education, dtype: object

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

In [32]:
df_full['age'].corr(df_full['balance'])

0.09778273937134775

In [33]:
df_full['day'].corr(df_full['campaign'])

0.16249021632619243

In [36]:
df_full['day'].corr(df_full['pdays'])

-0.0930440737729408

In [37]:
df_full['pdays'].corr(df_full['previous'])

0.4548196354805004

In [39]:
df_full.y

0         no
1         no
2         no
3         no
4         no
        ... 
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: y, Length: 45211, dtype: object

In [40]:
df_full.y = (df_full.y == 'yes').astype(int)

C:\Users\srira\AppData\Local\Temp\ipykernel_15436\2325281576.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full.y = (df_full.y == 'yes').astype(int)


In [41]:
df_full.y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int32

In [42]:
from sklearn.model_selection import train_test_split

In [44]:
df_full_train, df_test = train_test_split(df_full, test_size = 0.2, random_state = 42)

In [45]:
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 42)

In [47]:
len(df_full), len(df_train)+len(df_val)+len(df_test)

(45211, 45211)

In [49]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

In [50]:
y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

In [51]:
del df_train['y']
del df_val['y']
del df_test['y']

In [52]:
df_train

age            job   marital  education  balance housing   contact  \
0       32     technician    single   tertiary     1100     yes  cellular   
1       38   entrepreneur   married  secondary        0     yes  cellular   
2       49    blue-collar   married  secondary     3309     yes  cellular   
3       37      housemaid   married    primary     2410      no  cellular   
4       31  self-employed   married   tertiary     3220      no  cellular   
...    ...            ...       ...        ...      ...     ...       ...   
27121   27       services    single  secondary      167      no  cellular   
27122   40     technician    single   tertiary      693      no  cellular   
27123   54     technician  divorced  secondary        0     yes   unknown   
27124   25       services    single  secondary     2311      no  cellular   
27125   30     management    single   tertiary       15      no  cellular   

       day month  duration  campaign  pdays  previous poutcome  
0       11   aug        67         1     -1         0  unknown  
1       17   nov       258         1     -1         0  unknown  
2       15   may       349         2     -1         0  unknown  
3        4   aug       315         1     -1         0  unknown  
4       26   aug        74         4     -1         0  unknown  
...    ...   ...       ...       ...    ...       ...      ...  
27121    8   jul       606         2     -1         0  unknown  
27122   30   jan       427         1     -1         0  unknown  
27123   16   may       161         1     -1         0  unknown  
27124   21   jul      1105         2     -1         0  unknown  
27125   26   aug       252         2     -1         0  unknown  

[27126 rows x 14 columns]

In [53]:
y_train

array([0, 0, 0, ..., 0, 1, 0])

In [55]:
numerical = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
categorical = ['job', 'marital', 'education', 'housing',
       'contact', 'month', 'poutcome']

In [56]:
df_full_train[categorical].nunique()

job          12
marital       3
education     4
housing       2
contact       3
month        12
poutcome      4
dtype: int64

In [57]:
from sklearn.metrics import mutual_info_score

In [63]:
mutual_info_score(df_full_train.month, df_full_train.y)

0.024773565917283587

In [64]:
def mutual_info_y_score(series):
    return mutual_info_score(series, df_full_train.y)

In [96]:
mf = (df_full_train[categorical].apply(mutual_info_y_score))
mf.sort_values(ascending=False).round(2)

poutcome     0.03
month        0.02
contact      0.01
housing      0.01
job          0.01
education    0.00
marital      0.00
dtype: float64

In [79]:
from sklearn.feature_extraction import DictVectorizer

In [80]:
dv = DictVectorizer(sparse = False)

In [81]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')

In [82]:
x_train = dv.fit_transform(train_dicts)

In [83]:
x_train

array([[3.200e+01, 1.100e+03, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.800e+01, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [4.900e+01, 3.309e+03, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [5.400e+01, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.500e+01, 2.311e+03, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.000e+01, 1.500e+01, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00]])

In [84]:
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [85]:
x_val = dv.fit_transform(val_dicts)

In [75]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [77]:
from sklearn.linear_model import LogisticRegression

In [78]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [86]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [87]:
model.intercept_[0]

-1.006449986188843

In [88]:
model.predict(x_train)

array([0, 0, 0, ..., 0, 1, 0])

In [89]:
y_pred = model.predict_proba(x_val)[:, 1]

In [90]:
y_pred

array([0.01266343, 0.00970127, 0.15305569, ..., 0.05395033, 0.00894818,
       0.28595793])

In [91]:
y_descision = (y_pred >= 0.5)
y_descision

array([False, False, False, ..., False, False, False])

In [99]:
baseline_accuracy = (y_val == y_descision).mean().round(2)
baseline_accuracy

0.9

In [120]:
features = dv.get_feature_names_out().tolist() 
features

['age',
 'balance',
 'campaign',
 'contact=cellular',
 'contact=telephone',
 'contact=unknown',
 'day',
 'duration',
 'education=primary',
 'education=secondary',
 'education=tertiary',
 'education=unknown',
 'housing=no',
 'housing=yes',
 'job=admin.',
 'job=blue-collar',
 'job=entrepreneur',
 'job=housemaid',
 'job=management',
 'job=retired',
 'job=self-employed',
 'job=services',
 'job=student',
 'job=technician',
 'job=unemployed',
 'job=unknown',
 'marital=divorced',
 'marital=married',
 'marital=single',
 'month=apr',
 'month=aug',
 'month=dec',
 'month=feb',
 'month=jan',
 'month=jul',
 'month=jun',
 'month=mar',
 'month=may',
 'month=nov',
 'month=oct',
 'month=sep',
 'pdays',
 'poutcome=failure',
 'poutcome=other',
 'poutcome=success',
 'poutcome=unknown',
 'previous']

In [126]:
accuracy_differences = {}

In [127]:
for feature in features:
    feature_indices = [i for i, f in enumerate(features) if f != feature]
    x_train_reduced = x_train[:, feature_indices]
    x_val_reduced = x_val[:, feature_indices]
    
    model.fit(x_train_reduced, y_train)
    
    y_pred_reduced = model.predict_proba(x_val_reduced)[:, 1]
    y_decision = (y_pred_reduced >= 0.5)
    reduced_accuracy = (y_val == y_descision).mean()
    
    accuracy_difference = baseline_accuracy - reduced_accuracy
    accuracy_differences[feature] = accuracy_difference

In [128]:
accuracy_differences

{'age': -0.0013492590134925875,
 'balance': -0.0013492590134925875,
 'campaign': -0.0013492590134925875,
 'contact=cellular': -0.0013492590134925875,
 'contact=telephone': -0.0013492590134925875,
 'contact=unknown': -0.0013492590134925875,
 'day': -0.0013492590134925875,
 'duration': -0.0013492590134925875,
 'education=primary': -0.0013492590134925875,
 'education=secondary': -0.0013492590134925875,
 'education=tertiary': -0.0013492590134925875,
 'education=unknown': -0.0013492590134925875,
 'housing=no': -0.0013492590134925875,
 'housing=yes': -0.0013492590134925875,
 'job=admin.': -0.0013492590134925875,
 'job=blue-collar': -0.0013492590134925875,
 'job=entrepreneur': -0.0013492590134925875,
 'job=housemaid': -0.0013492590134925875,
 'job=management': -0.0013492590134925875,
 'job=retired': -0.0013492590134925875,
 'job=self-employed': -0.0013492590134925875,
 'job=services': -0.0013492590134925875,
 'job=student': -0.0013492590134925875,
 'job=technician': -0.0013492590134925875,
 '

In [129]:
least_useful_feature = min(accuracy_differences, key=accuracy_differences.get)
least_difference = accuracy_differences[least_useful_feature]

In [130]:
least_useful_feature

'age'

In [133]:
least_difference

-0.0013492590134925875

In [134]:
accuracy_results = {}
C_values = [0.01, 0.1, 1, 10, 100]

In [135]:
for C in C_values:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    
    model.fit(x_train, y_train)

    y_pred = model.predict_proba(x_val)[:, 1]
    
    y_decision = (y_pred >= 0.5)
    accuracy = (y_val == y_descision).mean()
    
    # Store the accuracy rounded to 3 decimal places
    accuracy_results[C] = round(accuracy, 3)

In [137]:
accuracy_results

{0.01: 0.901, 0.1: 0.901, 1: 0.901, 10: 0.901, 100: 0.901}